[package]
name = "detestable-me"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["macros", "time", "rt"] }

[dev-dependencies]
test-context = "0.4.1"
