[package]
name = "evilmgmt"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.7"
http-body-util = "0.1.3"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
tower = { version = "0.5.2", features = ["util"] }

[lints]
workspace = true
